name: media-management
services:
  common-tailscale-sidecar:
    image: tailscale/tailscale:latest
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    networks:
      - services
  deluge:
    container_name: deluge
    image: binhex/arch-delugevpn
#    expose:
#      - 8118
#      - 58846
#      - 58946
#    ports:
#      - 8112:8112
    volumes:
      - ${APPDATA_PATH}/deluge:/config
      - ${DOWNLOADS_DIR}:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      VPN_ENABLED: ${VPN_ENABLED}
      VPN_USER: ${VPN_USER}
      VPN_PASS: ${VPN_PASS}
      VPN_PROV: ${VPN_PROV}
      VPN_CLIENT: ${VPN_CLIENT}
      VPN_OPTIONS: ${VPN_OPTIONS}
      STRICT_PORT_FORWARD: ${STRICT_PORT_FORWARD}
      ENABLE_PRIVOXY: ${ENABLE_PRIVOXY}
      LAN_NETWORK: ${LAN_NETWORK}
      NAME_SERVERS: ${NAME_SERVERS}
      DELUGE_DAEMON_LOG_LEVEL: ${DELUGE_DAEMON_LOG_LEVEL}
      DELUGE_WEB_LOG_LEVEL: ${DELUGE_WEB_LOG_LEVEL}
      DELUGE_ENABLE_WEBUI_PASSWORD: ${DELUGE_ENABLE_WEBUI_PASSWORD}
      ADDITIONAL_PORTS: ${ADDITIONAL_PORTS}
      DEBUG: ${DEBUG}
      UMASK: ${UMASK}
      PUID: ${PUID}
      PGID: ${PGID}
      VIRTUAL_HOST: deluge
      VIRTUAL_PORT: 8112
    # For wireguard
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    # For openvpn
    #cap_add:
    #  - NET_ADMIN
    depends_on:
      - deluge-tailscale-sidecar
    network_mode: service:deluge-tailscale-sidecar
#    networks:
#      - services
  deluge-tailscale-sidecar:
    extends:
      service: common-tailscale-sidecar
    hostname: deluge
    container_name: deluge-tailscale-sidecar
    expose:
      - 8112
      - 8118
      - 58846
      - 58946
    volumes:
      - "${APPDATA_PATH}/tailscale_deluge_var_lib:/var/lib/tailscale"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      - VIRTUAL_HOST=tv
    volumes:
      - ${APPDATA_PATH}/sonarr:/config
      - ${DOWNLOADS_DIR}:/data
#    ports:
#      - 8989:8989
    restart: unless-stopped
    depends_on:
      - sonarr-tailscale-sidecar
    network_mode: service:sonarr-tailscale-sidecar
#    networks:
#      - services
  sonarr-tailscale-sidecar:
    extends:
      service: common-tailscale-sidecar
    hostname: tv
    container_name: sonarr-tailscale-sidecar
    volumes:
      - "${APPDATA_PATH}/tailscale_sonarr_var_lib:/var/lib/tailscale"
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      - VIRTUAL_HOST=movies
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${DOWNLOADS_DIR}:/data
#    ports:
#      - 7878:7878
    restart: unless-stopped
    depends_on:
      - radarr-tailscale-sidecar
    network_mode: service:radarr-tailscale-sidecar
#    networks:
#      - services
  radarr-tailscale-sidecar:
    extends:
      service: common-tailscale-sidecar
    hostname: movies
    container_name: radarr-tailscale-sidecar
    volumes:
      - "${APPDATA_PATH}/tailscale_radarr_var_lib:/var/lib/tailscale"
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      - VIRTUAL_HOST=music
    volumes:
      - ${APPDATA_PATH}/lidarr:/config
      - ${DOWNLOADS_DIR}:/data
#    ports:
#      - 8686:8686
    restart: unless-stopped
    depends_on:
      - lidarr-tailscale-sidecar
    network_mode: service:lidarr-tailscale-sidecar
#    networks:
#      - services
  lidarr-tailscale-sidecar:
    extends:
      service: common-tailscale-sidecar
    hostname: music
    container_name: lidarr-tailscale-sidecar
    volumes:
      - "${APPDATA_PATH}/tailscale_lidarr_var_lib:/var/lib/tailscale"
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      - VIRTUAL_HOST=indexers
    volumes:
      - ${APPDATA_PATH}/prowlarr:/config
#    ports:
#      - 9696:9696
    restart: unless-stopped
    depends_on:
      - prowlarr-tailscale-sidecar
    network_mode: service:prowlarr-tailscale-sidecar
#    networks:
#      - services
  prowlarr-tailscale-sidecar:
    extends:
      service: common-tailscale-sidecar
    hostname: indexers
    container_name: indexers-tailscale-sidecar
    volumes:
      - "${APPDATA_PATH}/tailscale_indexers_var_lib:/var/lib/tailscale"

networks:
  services:
    name: services
    external: true
env_files:
  - path: base.env
  - path: media-management.env
  - path: secret.secret
