name: media-players
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
#    ports:
#      - 8096:8096
    environment:
      - VIRTUAL_HOST=jellyfin
    volumes:
      - ${APPDATA_PATH}/jellyfin:/config
      - ${APPDATA_PATH}/jellyfin-cache:/cache
      - /srv/dev-disk-by-label-nas2020/media:/media
    restart: 'unless-stopped'
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - jellyfin-tailscale-sidecar
    network_mode: service:jellyfin-tailscale-sidecar
#    networks:
#      - services
  jellyfin-tailscale-sidecar:
    hostname: jellyfin
    container_name: jellyfin-tailscale-sidecar
    image: tailscale/tailscale:latest
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - "${APPDATA_PATH}/tailscale_jellyfin_var_lib:/var/lib/tailscale"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    name: services
    external: true
    # Optional - alternative address used for autodiscovery
    #environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
env_file:
  - path: base.env
  - path: secret.secret
